require 'minitest/autorun'
require 'interesting_methods'
require 'interesting_methods/version'
require 'test_objects/animal'
require 'test_objects/colours'
require 'test_objects/pig'
require 'test_objects/pig_with_colours_extended'
require 'test_objects/pig_with_colours_included'
